[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ChemEmbed"
version = "0.1.0"
description = "A deep learning framework for metabolite identification using enhanced MS/MS data and multidimensional molecular embeddings"
readme = "README.md"
license = "MIT"
requires-python = ">=3.6"
authors = [
    { name = "Muhammad Faizan Khan" }
]

dependencies = [
    "numpy>=1.18.0",
    "pandas>=1.0.0",
    "scipy>=1.4.0",
    "torch>=1.5.0",
    "torchvision>=0.21.0",
    "pyYAML>=5.3.0",
    "rdkit >=2020.09.1",
]

[project.scripts]
ChemEmbed = "cli:main"

[tool.setuptools]
py-modules = ["cli", "data_processing", "model_utils", "reference_utils", "chemembed_single_file"]

[tool.setuptools.packages.find]
where = ["."]